//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NETCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;

    public partial class tblDiseño
    {
        public int idDiseño { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<double> precio { get; set; }
        public string talla { get; set; }
        public string color { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string marca { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
    }
}
